/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 38.0.2 Tue Jun 27 15:29:44 2023.
 */

#include <string.h>

#include "sc22_evo_canlv.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t unpack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) << shift);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int sc22_evo_canlv_steering_rtd_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_steering_rtd_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->rtd_cmd, 0u, 0xffu);

    return (1);
}

int sc22_evo_canlv_steering_rtd_unpack(
    struct sc22_evo_canlv_steering_rtd_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->rtd_cmd = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

uint8_t sc22_evo_canlv_steering_rtd_rtd_cmd_encode(float value)
{
    return (uint8_t)(value);
}

float sc22_evo_canlv_steering_rtd_rtd_cmd_decode(uint8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_steering_rtd_rtd_cmd_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sc22_evo_canlv_steering_motor_control_debug_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_steering_motor_control_debug_t *src_p,
    size_t size)
{
    uint8_t front_left_on;
    uint8_t front_right_on;
    uint8_t rear_left_on;
    uint8_t rear_right_on;

    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    front_left_on = (uint8_t)src_p->front_left_on;
    dst_p[0] |= pack_left_shift_u8(front_left_on, 0u, 0x01u);
    front_right_on = (uint8_t)src_p->front_right_on;
    dst_p[0] |= pack_left_shift_u8(front_right_on, 1u, 0x02u);
    rear_left_on = (uint8_t)src_p->rear_left_on;
    dst_p[0] |= pack_left_shift_u8(rear_left_on, 2u, 0x04u);
    rear_right_on = (uint8_t)src_p->rear_right_on;
    dst_p[0] |= pack_left_shift_u8(rear_right_on, 3u, 0x08u);

    return (1);
}

int sc22_evo_canlv_steering_motor_control_debug_unpack(
    struct sc22_evo_canlv_steering_motor_control_debug_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t front_left_on;
    uint8_t front_right_on;
    uint8_t rear_left_on;
    uint8_t rear_right_on;

    if (size < 1u) {
        return (-EINVAL);
    }

    front_left_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    if ((front_left_on & (1u << 0)) != 0u) {
        front_left_on |= 0xfeu;
    }

    dst_p->front_left_on = (int8_t)front_left_on;
    front_right_on = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    if ((front_right_on & (1u << 0)) != 0u) {
        front_right_on |= 0xfeu;
    }

    dst_p->front_right_on = (int8_t)front_right_on;
    rear_left_on = unpack_right_shift_u8(src_p[0], 2u, 0x04u);

    if ((rear_left_on & (1u << 0)) != 0u) {
        rear_left_on |= 0xfeu;
    }

    dst_p->rear_left_on = (int8_t)rear_left_on;
    rear_right_on = unpack_right_shift_u8(src_p[0], 3u, 0x08u);

    if ((rear_right_on & (1u << 0)) != 0u) {
        rear_right_on |= 0xfeu;
    }

    dst_p->rear_right_on = (int8_t)rear_right_on;

    return (0);
}

int8_t sc22_evo_canlv_steering_motor_control_debug_front_left_on_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_steering_motor_control_debug_front_left_on_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_steering_motor_control_debug_front_left_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_steering_motor_control_debug_front_right_on_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_steering_motor_control_debug_front_right_on_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_steering_motor_control_debug_front_right_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_steering_motor_control_debug_rear_left_on_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_steering_motor_control_debug_rear_left_on_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_steering_motor_control_debug_rear_left_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_steering_motor_control_debug_rear_right_on_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_steering_motor_control_debug_rear_right_on_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_steering_motor_control_debug_rear_right_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int sc22_evo_canlv_bmslv_temp1_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_bmslv_temp1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->ntc1_resistance, 1u, 0xfeu);
    dst_p[1] |= pack_right_shift_u16(src_p->ntc1_resistance, 7u, 0x07u);
    dst_p[1] |= pack_left_shift_u16(src_p->ntc2_resistance, 3u, 0xf8u);
    dst_p[2] |= pack_right_shift_u16(src_p->ntc2_resistance, 5u, 0x1fu);
    dst_p[2] |= pack_left_shift_u16(src_p->ntc3_resistance, 5u, 0xe0u);
    dst_p[3] |= pack_right_shift_u16(src_p->ntc3_resistance, 3u, 0x7fu);
    dst_p[3] |= pack_left_shift_u16(src_p->ntc4_resistance, 7u, 0x80u);
    dst_p[4] |= pack_right_shift_u16(src_p->ntc4_resistance, 1u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->ntc4_resistance, 9u, 0x01u);
    dst_p[5] |= pack_left_shift_u16(src_p->ntc5_resistance, 1u, 0xfeu);
    dst_p[6] |= pack_right_shift_u16(src_p->ntc5_resistance, 7u, 0x07u);
    dst_p[6] |= pack_left_shift_u16(src_p->ntc6_resistance, 6u, 0xc0u);
    dst_p[7] |= pack_right_shift_u16(src_p->ntc6_resistance, 2u, 0xffu);

    return (8);
}

int sc22_evo_canlv_bmslv_temp1_unpack(
    struct sc22_evo_canlv_bmslv_temp1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ntc1_resistance = unpack_right_shift_u16(src_p[0], 1u, 0xfeu);
    dst_p->ntc1_resistance |= unpack_left_shift_u16(src_p[1], 7u, 0x07u);
    dst_p->ntc2_resistance = unpack_right_shift_u16(src_p[1], 3u, 0xf8u);
    dst_p->ntc2_resistance |= unpack_left_shift_u16(src_p[2], 5u, 0x1fu);
    dst_p->ntc3_resistance = unpack_right_shift_u16(src_p[2], 5u, 0xe0u);
    dst_p->ntc3_resistance |= unpack_left_shift_u16(src_p[3], 3u, 0x7fu);
    dst_p->ntc4_resistance = unpack_right_shift_u16(src_p[3], 7u, 0x80u);
    dst_p->ntc4_resistance |= unpack_left_shift_u16(src_p[4], 1u, 0xffu);
    dst_p->ntc4_resistance |= unpack_left_shift_u16(src_p[5], 9u, 0x01u);
    dst_p->ntc5_resistance = unpack_right_shift_u16(src_p[5], 1u, 0xfeu);
    dst_p->ntc5_resistance |= unpack_left_shift_u16(src_p[6], 7u, 0x07u);
    dst_p->ntc6_resistance = unpack_right_shift_u16(src_p[6], 6u, 0xc0u);
    dst_p->ntc6_resistance |= unpack_left_shift_u16(src_p[7], 2u, 0xffu);

    return (0);
}

uint16_t sc22_evo_canlv_bmslv_temp1_ntc1_resistance_encode(float value)
{
    return (uint16_t)((value - 1000.0f) / 31.250000f);
}

float sc22_evo_canlv_bmslv_temp1_ntc1_resistance_decode(uint16_t value)
{
    return (((float)value * 31.250000f) + 1000.0f);
}

bool sc22_evo_canlv_bmslv_temp1_ntc1_resistance_is_in_range(uint16_t value)
{
    return (value <= 991u);
}

uint16_t sc22_evo_canlv_bmslv_temp1_ntc2_resistance_encode(float value)
{
    return (uint16_t)((value - 1000.0f) / 31.250000f);
}

float sc22_evo_canlv_bmslv_temp1_ntc2_resistance_decode(uint16_t value)
{
    return (((float)value * 31.250000f) + 1000.0f);
}

bool sc22_evo_canlv_bmslv_temp1_ntc2_resistance_is_in_range(uint16_t value)
{
    return (value <= 991u);
}

uint16_t sc22_evo_canlv_bmslv_temp1_ntc3_resistance_encode(float value)
{
    return (uint16_t)((value - 1000.0f) / 31.250000f);
}

float sc22_evo_canlv_bmslv_temp1_ntc3_resistance_decode(uint16_t value)
{
    return (((float)value * 31.250000f) + 1000.0f);
}

bool sc22_evo_canlv_bmslv_temp1_ntc3_resistance_is_in_range(uint16_t value)
{
    return (value <= 991u);
}

uint16_t sc22_evo_canlv_bmslv_temp1_ntc4_resistance_encode(float value)
{
    return (uint16_t)((value - 1000.0f) / 31.250000f);
}

float sc22_evo_canlv_bmslv_temp1_ntc4_resistance_decode(uint16_t value)
{
    return (((float)value * 31.250000f) + 1000.0f);
}

bool sc22_evo_canlv_bmslv_temp1_ntc4_resistance_is_in_range(uint16_t value)
{
    return (value <= 991u);
}

uint16_t sc22_evo_canlv_bmslv_temp1_ntc5_resistance_encode(float value)
{
    return (uint16_t)((value - 1000.0f) / 31.250000f);
}

float sc22_evo_canlv_bmslv_temp1_ntc5_resistance_decode(uint16_t value)
{
    return (((float)value * 31.250000f) + 1000.0f);
}

bool sc22_evo_canlv_bmslv_temp1_ntc5_resistance_is_in_range(uint16_t value)
{
    return (value <= 991u);
}

uint16_t sc22_evo_canlv_bmslv_temp1_ntc6_resistance_encode(float value)
{
    return (uint16_t)((value - 1000.0f) / 31.250000f);
}

float sc22_evo_canlv_bmslv_temp1_ntc6_resistance_decode(uint16_t value)
{
    return (((float)value * 31.250000f) + 1000.0f);
}

bool sc22_evo_canlv_bmslv_temp1_ntc6_resistance_is_in_range(uint16_t value)
{
    return (value <= 991u);
}

int sc22_evo_canlv_bmslv_temp2_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_bmslv_temp2_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->ntc1_resistance, 1u, 0xfeu);
    dst_p[1] |= pack_right_shift_u16(src_p->ntc1_resistance, 7u, 0x07u);
    dst_p[1] |= pack_left_shift_u16(src_p->ntc2_resistance, 3u, 0xf8u);
    dst_p[2] |= pack_right_shift_u16(src_p->ntc2_resistance, 5u, 0x1fu);
    dst_p[2] |= pack_left_shift_u16(src_p->ntc3_resistance, 5u, 0xe0u);
    dst_p[3] |= pack_right_shift_u16(src_p->ntc3_resistance, 3u, 0x7fu);
    dst_p[3] |= pack_left_shift_u16(src_p->ntc4_resistance, 7u, 0x80u);
    dst_p[4] |= pack_right_shift_u16(src_p->ntc4_resistance, 1u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->ntc4_resistance, 9u, 0x01u);
    dst_p[5] |= pack_left_shift_u16(src_p->ntc5_resistance, 1u, 0xfeu);
    dst_p[6] |= pack_right_shift_u16(src_p->ntc5_resistance, 7u, 0x07u);
    dst_p[6] |= pack_left_shift_u16(src_p->ntc6_resistance, 6u, 0xc0u);
    dst_p[7] |= pack_right_shift_u16(src_p->ntc6_resistance, 2u, 0xffu);

    return (8);
}

int sc22_evo_canlv_bmslv_temp2_unpack(
    struct sc22_evo_canlv_bmslv_temp2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ntc1_resistance = unpack_right_shift_u16(src_p[0], 1u, 0xfeu);
    dst_p->ntc1_resistance |= unpack_left_shift_u16(src_p[1], 7u, 0x07u);
    dst_p->ntc2_resistance = unpack_right_shift_u16(src_p[1], 3u, 0xf8u);
    dst_p->ntc2_resistance |= unpack_left_shift_u16(src_p[2], 5u, 0x1fu);
    dst_p->ntc3_resistance = unpack_right_shift_u16(src_p[2], 5u, 0xe0u);
    dst_p->ntc3_resistance |= unpack_left_shift_u16(src_p[3], 3u, 0x7fu);
    dst_p->ntc4_resistance = unpack_right_shift_u16(src_p[3], 7u, 0x80u);
    dst_p->ntc4_resistance |= unpack_left_shift_u16(src_p[4], 1u, 0xffu);
    dst_p->ntc4_resistance |= unpack_left_shift_u16(src_p[5], 9u, 0x01u);
    dst_p->ntc5_resistance = unpack_right_shift_u16(src_p[5], 1u, 0xfeu);
    dst_p->ntc5_resistance |= unpack_left_shift_u16(src_p[6], 7u, 0x07u);
    dst_p->ntc6_resistance = unpack_right_shift_u16(src_p[6], 6u, 0xc0u);
    dst_p->ntc6_resistance |= unpack_left_shift_u16(src_p[7], 2u, 0xffu);

    return (0);
}

uint16_t sc22_evo_canlv_bmslv_temp2_ntc1_resistance_encode(float value)
{
    return (uint16_t)((value - 1000.0f) / 31.250000f);
}

float sc22_evo_canlv_bmslv_temp2_ntc1_resistance_decode(uint16_t value)
{
    return (((float)value * 31.250000f) + 1000.0f);
}

bool sc22_evo_canlv_bmslv_temp2_ntc1_resistance_is_in_range(uint16_t value)
{
    return (value <= 991u);
}

uint16_t sc22_evo_canlv_bmslv_temp2_ntc2_resistance_encode(float value)
{
    return (uint16_t)((value - 1000.0f) / 31.250000f);
}

float sc22_evo_canlv_bmslv_temp2_ntc2_resistance_decode(uint16_t value)
{
    return (((float)value * 31.250000f) + 1000.0f);
}

bool sc22_evo_canlv_bmslv_temp2_ntc2_resistance_is_in_range(uint16_t value)
{
    return (value <= 991u);
}

uint16_t sc22_evo_canlv_bmslv_temp2_ntc3_resistance_encode(float value)
{
    return (uint16_t)((value - 1000.0f) / 31.250000f);
}

float sc22_evo_canlv_bmslv_temp2_ntc3_resistance_decode(uint16_t value)
{
    return (((float)value * 31.250000f) + 1000.0f);
}

bool sc22_evo_canlv_bmslv_temp2_ntc3_resistance_is_in_range(uint16_t value)
{
    return (value <= 991u);
}

uint16_t sc22_evo_canlv_bmslv_temp2_ntc4_resistance_encode(float value)
{
    return (uint16_t)((value - 1000.0f) / 31.250000f);
}

float sc22_evo_canlv_bmslv_temp2_ntc4_resistance_decode(uint16_t value)
{
    return (((float)value * 31.250000f) + 1000.0f);
}

bool sc22_evo_canlv_bmslv_temp2_ntc4_resistance_is_in_range(uint16_t value)
{
    return (value <= 991u);
}

uint16_t sc22_evo_canlv_bmslv_temp2_ntc5_resistance_encode(float value)
{
    return (uint16_t)((value - 1000.0f) / 31.250000f);
}

float sc22_evo_canlv_bmslv_temp2_ntc5_resistance_decode(uint16_t value)
{
    return (((float)value * 31.250000f) + 1000.0f);
}

bool sc22_evo_canlv_bmslv_temp2_ntc5_resistance_is_in_range(uint16_t value)
{
    return (value <= 991u);
}

uint16_t sc22_evo_canlv_bmslv_temp2_ntc6_resistance_encode(float value)
{
    return (uint16_t)((value - 1000.0f) / 31.250000f);
}

float sc22_evo_canlv_bmslv_temp2_ntc6_resistance_decode(uint16_t value)
{
    return (((float)value * 31.250000f) + 1000.0f);
}

bool sc22_evo_canlv_bmslv_temp2_ntc6_resistance_is_in_range(uint16_t value)
{
    return (value <= 991u);
}

int sc22_evo_canlv_bmslv_cell_voltage1_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_bmslv_cell_voltage1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->cell_1_voltage_m_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cell_1_voltage_m_v, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->cell_2_voltage_m_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->cell_2_voltage_m_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell_3_voltage_m_v, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->cell_3_voltage_m_v, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->cell_4_voltage_m_v, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->cell_4_voltage_m_v, 8u, 0xffu);

    return (8);
}

int sc22_evo_canlv_bmslv_cell_voltage1_unpack(
    struct sc22_evo_canlv_bmslv_cell_voltage1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->cell_1_voltage_m_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cell_1_voltage_m_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->cell_2_voltage_m_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->cell_2_voltage_m_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->cell_3_voltage_m_v = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->cell_3_voltage_m_v |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->cell_4_voltage_m_v = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->cell_4_voltage_m_v |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t sc22_evo_canlv_bmslv_cell_voltage1_cell_1_voltage_m_v_encode(float value)
{
    return (uint16_t)((value - 2000.0f) / 0.038000f);
}

float sc22_evo_canlv_bmslv_cell_voltage1_cell_1_voltage_m_v_decode(uint16_t value)
{
    return (((float)value * 0.038000f) + 2000.0f);
}

bool sc22_evo_canlv_bmslv_cell_voltage1_cell_1_voltage_m_v_is_in_range(uint16_t value)
{
    return (value <= 12903u);
}

uint16_t sc22_evo_canlv_bmslv_cell_voltage1_cell_2_voltage_m_v_encode(float value)
{
    return (uint16_t)((value - 2000.0f) / 0.038000f);
}

float sc22_evo_canlv_bmslv_cell_voltage1_cell_2_voltage_m_v_decode(uint16_t value)
{
    return (((float)value * 0.038000f) + 2000.0f);
}

bool sc22_evo_canlv_bmslv_cell_voltage1_cell_2_voltage_m_v_is_in_range(uint16_t value)
{
    return (value <= 12903u);
}

uint16_t sc22_evo_canlv_bmslv_cell_voltage1_cell_3_voltage_m_v_encode(float value)
{
    return (uint16_t)((value - 2000.0f) / 0.038000f);
}

float sc22_evo_canlv_bmslv_cell_voltage1_cell_3_voltage_m_v_decode(uint16_t value)
{
    return (((float)value * 0.038000f) + 2000.0f);
}

bool sc22_evo_canlv_bmslv_cell_voltage1_cell_3_voltage_m_v_is_in_range(uint16_t value)
{
    return (value <= 12903u);
}

uint16_t sc22_evo_canlv_bmslv_cell_voltage1_cell_4_voltage_m_v_encode(float value)
{
    return (uint16_t)((value - 2000.0f) / 0.038000f);
}

float sc22_evo_canlv_bmslv_cell_voltage1_cell_4_voltage_m_v_decode(uint16_t value)
{
    return (((float)value * 0.038000f) + 2000.0f);
}

bool sc22_evo_canlv_bmslv_cell_voltage1_cell_4_voltage_m_v_is_in_range(uint16_t value)
{
    return (value <= 12903u);
}

int sc22_evo_canlv_bmslv_cell_voltage2_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_bmslv_cell_voltage2_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->cell_5_voltage_m_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cell_5_voltage_m_v, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->cell_6_voltage_m_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->cell_6_voltage_m_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->cell_7_voltage_m_v, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->cell_7_voltage_m_v, 8u, 0xffu);

    return (6);
}

int sc22_evo_canlv_bmslv_cell_voltage2_unpack(
    struct sc22_evo_canlv_bmslv_cell_voltage2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->cell_5_voltage_m_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cell_5_voltage_m_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->cell_6_voltage_m_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->cell_6_voltage_m_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->cell_7_voltage_m_v = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->cell_7_voltage_m_v |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

uint16_t sc22_evo_canlv_bmslv_cell_voltage2_cell_5_voltage_m_v_encode(float value)
{
    return (uint16_t)((value - 2000.0f) / 0.038000f);
}

float sc22_evo_canlv_bmslv_cell_voltage2_cell_5_voltage_m_v_decode(uint16_t value)
{
    return (((float)value * 0.038000f) + 2000.0f);
}

bool sc22_evo_canlv_bmslv_cell_voltage2_cell_5_voltage_m_v_is_in_range(uint16_t value)
{
    return (value <= 12903u);
}

uint16_t sc22_evo_canlv_bmslv_cell_voltage2_cell_6_voltage_m_v_encode(float value)
{
    return (uint16_t)((value - 2000.0f) / 0.038000f);
}

float sc22_evo_canlv_bmslv_cell_voltage2_cell_6_voltage_m_v_decode(uint16_t value)
{
    return (((float)value * 0.038000f) + 2000.0f);
}

bool sc22_evo_canlv_bmslv_cell_voltage2_cell_6_voltage_m_v_is_in_range(uint16_t value)
{
    return (value <= 12903u);
}

uint16_t sc22_evo_canlv_bmslv_cell_voltage2_cell_7_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_bmslv_cell_voltage2_cell_7_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_bmslv_cell_voltage2_cell_7_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int sc22_evo_canlv_bmslv_battery_pack_general_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_bmslv_battery_pack_general_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->current_sensor_voltage, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->current_sensor_voltage, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->lv_total_voltage_m_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->lv_total_voltage_m_v, 8u, 0xffu);

    return (4);
}

int sc22_evo_canlv_bmslv_battery_pack_general_unpack(
    struct sc22_evo_canlv_bmslv_battery_pack_general_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->current_sensor_voltage = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->current_sensor_voltage |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->lv_total_voltage_m_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->lv_total_voltage_m_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

uint16_t sc22_evo_canlv_bmslv_battery_pack_general_current_sensor_voltage_encode(float value)
{
    return (uint16_t)(value / 0.076000f);
}

float sc22_evo_canlv_bmslv_battery_pack_general_current_sensor_voltage_decode(uint16_t value)
{
    return ((float)value * 0.076000f);
}

bool sc22_evo_canlv_bmslv_battery_pack_general_current_sensor_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_bmslv_battery_pack_general_lv_total_voltage_m_v_encode(float value)
{
    return (uint16_t)((value - 14000.0f) / 0.267000f);
}

float sc22_evo_canlv_bmslv_battery_pack_general_lv_total_voltage_m_v_decode(uint16_t value)
{
    return (((float)value * 0.267000f) + 14000.0f);
}

bool sc22_evo_canlv_bmslv_battery_pack_general_lv_total_voltage_m_v_is_in_range(uint16_t value)
{
    return (value <= 13100u);
}

int sc22_evo_canlv_bmslv_status_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_bmslv_status_t *src_p,
    size_t size)
{
    uint8_t is_relay_open;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    is_relay_open = (uint8_t)src_p->is_relay_open;
    dst_p[0] |= pack_left_shift_u8(is_relay_open, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->bmslv_status_message, 1u, 0xfeu);
    dst_p[1] |= pack_right_shift_u8(src_p->bmslv_status_message, 7u, 0x01u);

    return (2);
}

int sc22_evo_canlv_bmslv_status_unpack(
    struct sc22_evo_canlv_bmslv_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t is_relay_open;

    if (size < 2u) {
        return (-EINVAL);
    }

    is_relay_open = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    if ((is_relay_open & (1u << 0)) != 0u) {
        is_relay_open |= 0xfeu;
    }

    dst_p->is_relay_open = (int8_t)is_relay_open;
    dst_p->bmslv_status_message = unpack_right_shift_u8(src_p[0], 1u, 0xfeu);
    dst_p->bmslv_status_message |= unpack_left_shift_u8(src_p[1], 7u, 0x01u);

    return (0);
}

int8_t sc22_evo_canlv_bmslv_status_is_relay_open_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_bmslv_status_is_relay_open_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_bmslv_status_is_relay_open_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

uint8_t sc22_evo_canlv_bmslv_status_bmslv_status_message_encode(float value)
{
    return (uint8_t)(value);
}

float sc22_evo_canlv_bmslv_status_bmslv_status_message_decode(uint8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_bmslv_status_bmslv_status_message_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sc22_evo_canlv_sens_front_1_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_sens_front_1_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->throttle_0_voltage_m_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->throttle_0_voltage_m_v, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->throttle_1_voltage_m_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->throttle_1_voltage_m_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->steering_voltage_m_v, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->steering_voltage_m_v, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->brake_straingauge_voltage_m_v, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->brake_straingauge_voltage_m_v, 8u, 0xffu);

    return (8);
}

int sc22_evo_canlv_sens_front_1_unpack(
    struct sc22_evo_canlv_sens_front_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->throttle_0_voltage_m_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->throttle_0_voltage_m_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->throttle_1_voltage_m_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->throttle_1_voltage_m_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->steering_voltage_m_v = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->steering_voltage_m_v |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->brake_straingauge_voltage_m_v = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->brake_straingauge_voltage_m_v |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t sc22_evo_canlv_sens_front_1_throttle_0_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_1_throttle_0_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_1_throttle_0_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_front_1_throttle_1_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_1_throttle_1_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_1_throttle_1_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_front_1_steering_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_1_steering_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_1_steering_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_front_1_brake_straingauge_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_1_brake_straingauge_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_1_brake_straingauge_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int sc22_evo_canlv_sens_front_2_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_sens_front_2_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->pot_fl_voltage_m_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->pot_fl_voltage_m_v, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->pot_fr_voltage_m_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->pot_fr_voltage_m_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->brake_pressure_voltage_m_v, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->brake_pressure_voltage_m_v, 8u, 0xffu);

    return (6);
}

int sc22_evo_canlv_sens_front_2_unpack(
    struct sc22_evo_canlv_sens_front_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->pot_fl_voltage_m_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->pot_fl_voltage_m_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->pot_fr_voltage_m_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->pot_fr_voltage_m_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->brake_pressure_voltage_m_v = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->brake_pressure_voltage_m_v |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

uint16_t sc22_evo_canlv_sens_front_2_pot_fl_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_2_pot_fl_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_2_pot_fl_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_front_2_pot_fr_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_2_pot_fr_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_2_pot_fr_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_front_2_brake_pressure_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_2_brake_pressure_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_2_brake_pressure_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int sc22_evo_canlv_sens_front_3_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_sens_front_3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->straingauge_push_fr_voltage_m_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->straingauge_push_fr_voltage_m_v, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->straingauge_tie_fr_voltage_m_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->straingauge_tie_fr_voltage_m_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->straingauge_push_fl_voltage_m_v, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->straingauge_push_fl_voltage_m_v, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->straingauge_tie_fl_voltage_m_v, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->straingauge_tie_fl_voltage_m_v, 8u, 0xffu);

    return (8);
}

int sc22_evo_canlv_sens_front_3_unpack(
    struct sc22_evo_canlv_sens_front_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->straingauge_push_fr_voltage_m_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->straingauge_push_fr_voltage_m_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->straingauge_tie_fr_voltage_m_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->straingauge_tie_fr_voltage_m_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->straingauge_push_fl_voltage_m_v = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->straingauge_push_fl_voltage_m_v |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->straingauge_tie_fl_voltage_m_v = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->straingauge_tie_fl_voltage_m_v |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t sc22_evo_canlv_sens_front_3_straingauge_push_fr_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_3_straingauge_push_fr_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_3_straingauge_push_fr_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_front_3_straingauge_tie_fr_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_3_straingauge_tie_fr_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_3_straingauge_tie_fr_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_front_3_straingauge_push_fl_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_3_straingauge_push_fl_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_3_straingauge_push_fl_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_front_3_straingauge_tie_fl_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_3_straingauge_tie_fl_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_3_straingauge_tie_fl_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int sc22_evo_canlv_sens_front_shutdown_status_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_sens_front_shutdown_status_t *src_p,
    size_t size)
{
    uint8_t is_shut_closed_post_bots;
    uint8_t is_shut_closed_post_cockpit;
    uint8_t is_shut_closed_post_inertia;
    uint8_t is_shut_closed_pre_inertia;

    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    is_shut_closed_pre_inertia = (uint8_t)src_p->is_shut_closed_pre_inertia;
    dst_p[0] |= pack_left_shift_u8(is_shut_closed_pre_inertia, 0u, 0x01u);
    is_shut_closed_post_inertia = (uint8_t)src_p->is_shut_closed_post_inertia;
    dst_p[0] |= pack_left_shift_u8(is_shut_closed_post_inertia, 1u, 0x02u);
    is_shut_closed_post_bots = (uint8_t)src_p->is_shut_closed_post_bots;
    dst_p[0] |= pack_left_shift_u8(is_shut_closed_post_bots, 2u, 0x04u);
    is_shut_closed_post_cockpit = (uint8_t)src_p->is_shut_closed_post_cockpit;
    dst_p[0] |= pack_left_shift_u8(is_shut_closed_post_cockpit, 3u, 0x08u);

    return (1);
}

int sc22_evo_canlv_sens_front_shutdown_status_unpack(
    struct sc22_evo_canlv_sens_front_shutdown_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t is_shut_closed_post_bots;
    uint8_t is_shut_closed_post_cockpit;
    uint8_t is_shut_closed_post_inertia;
    uint8_t is_shut_closed_pre_inertia;

    if (size < 1u) {
        return (-EINVAL);
    }

    is_shut_closed_pre_inertia = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    if ((is_shut_closed_pre_inertia & (1u << 0)) != 0u) {
        is_shut_closed_pre_inertia |= 0xfeu;
    }

    dst_p->is_shut_closed_pre_inertia = (int8_t)is_shut_closed_pre_inertia;
    is_shut_closed_post_inertia = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    if ((is_shut_closed_post_inertia & (1u << 0)) != 0u) {
        is_shut_closed_post_inertia |= 0xfeu;
    }

    dst_p->is_shut_closed_post_inertia = (int8_t)is_shut_closed_post_inertia;
    is_shut_closed_post_bots = unpack_right_shift_u8(src_p[0], 2u, 0x04u);

    if ((is_shut_closed_post_bots & (1u << 0)) != 0u) {
        is_shut_closed_post_bots |= 0xfeu;
    }

    dst_p->is_shut_closed_post_bots = (int8_t)is_shut_closed_post_bots;
    is_shut_closed_post_cockpit = unpack_right_shift_u8(src_p[0], 3u, 0x08u);

    if ((is_shut_closed_post_cockpit & (1u << 0)) != 0u) {
        is_shut_closed_post_cockpit |= 0xfeu;
    }

    dst_p->is_shut_closed_post_cockpit = (int8_t)is_shut_closed_post_cockpit;

    return (0);
}

int8_t sc22_evo_canlv_sens_front_shutdown_status_is_shut_closed_pre_inertia_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_sens_front_shutdown_status_is_shut_closed_pre_inertia_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_shutdown_status_is_shut_closed_pre_inertia_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_sens_front_shutdown_status_is_shut_closed_post_inertia_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_sens_front_shutdown_status_is_shut_closed_post_inertia_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_shutdown_status_is_shut_closed_post_inertia_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_sens_front_shutdown_status_is_shut_closed_post_bots_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_sens_front_shutdown_status_is_shut_closed_post_bots_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_shutdown_status_is_shut_closed_post_bots_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_sens_front_shutdown_status_is_shut_closed_post_cockpit_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_sens_front_shutdown_status_is_shut_closed_post_cockpit_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_shutdown_status_is_shut_closed_post_cockpit_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int sc22_evo_canlv_sens_front_ntc_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_sens_front_ntc_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->ntc_resistance, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->ntc_resistance, 8u, 0x03u);
    dst_p[1] |= pack_left_shift_u16(src_p->ntc_2_resistance, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(src_p->ntc_2_resistance, 6u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->ntc_3_resistance, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(src_p->ntc_3_resistance, 4u, 0x3fu);
    dst_p[3] |= pack_left_shift_u16(src_p->ntc_4_resistance, 6u, 0xc0u);
    dst_p[4] |= pack_right_shift_u16(src_p->ntc_4_resistance, 2u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->ntc_spare1_resistance, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->ntc_spare1_resistance, 8u, 0x03u);
    dst_p[6] |= pack_left_shift_u16(src_p->ntc_spare2_resistance, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(src_p->ntc_spare2_resistance, 6u, 0x0fu);

    return (8);
}

int sc22_evo_canlv_sens_front_ntc_unpack(
    struct sc22_evo_canlv_sens_front_ntc_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ntc_resistance = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->ntc_resistance |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);
    dst_p->ntc_2_resistance = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    dst_p->ntc_2_resistance |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);
    dst_p->ntc_3_resistance = unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    dst_p->ntc_3_resistance |= unpack_left_shift_u16(src_p[3], 4u, 0x3fu);
    dst_p->ntc_4_resistance = unpack_right_shift_u16(src_p[3], 6u, 0xc0u);
    dst_p->ntc_4_resistance |= unpack_left_shift_u16(src_p[4], 2u, 0xffu);
    dst_p->ntc_spare1_resistance = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->ntc_spare1_resistance |= unpack_left_shift_u16(src_p[6], 8u, 0x03u);
    dst_p->ntc_spare2_resistance = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    dst_p->ntc_spare2_resistance |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);

    return (0);
}

uint16_t sc22_evo_canlv_sens_front_ntc_ntc_resistance_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_ntc_ntc_resistance_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_ntc_ntc_resistance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t sc22_evo_canlv_sens_front_ntc_ntc_2_resistance_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_ntc_ntc_2_resistance_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_ntc_ntc_2_resistance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t sc22_evo_canlv_sens_front_ntc_ntc_3_resistance_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_ntc_ntc_3_resistance_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_ntc_ntc_3_resistance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t sc22_evo_canlv_sens_front_ntc_ntc_4_resistance_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_ntc_ntc_4_resistance_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_ntc_ntc_4_resistance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t sc22_evo_canlv_sens_front_ntc_ntc_spare1_resistance_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_ntc_ntc_spare1_resistance_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_ntc_ntc_spare1_resistance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t sc22_evo_canlv_sens_front_ntc_ntc_spare2_resistance_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_front_ntc_ntc_spare2_resistance_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_front_ntc_ntc_spare2_resistance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int sc22_evo_canlv_sens_rear_1_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_sens_rear_1_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u16(src_p->pot_rl_voltage_m_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->pot_rl_voltage_m_v, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->pot_rr_voltage_rr, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->pot_rr_voltage_rr, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->brake_pressure_rear_voltage_m_v, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->brake_pressure_rear_voltage_m_v, 8u, 0xffu);

    return (6);
}

int sc22_evo_canlv_sens_rear_1_unpack(
    struct sc22_evo_canlv_sens_rear_1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->pot_rl_voltage_m_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->pot_rl_voltage_m_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->pot_rr_voltage_rr = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->pot_rr_voltage_rr |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->brake_pressure_rear_voltage_m_v = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->brake_pressure_rear_voltage_m_v |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);

    return (0);
}

uint16_t sc22_evo_canlv_sens_rear_1_pot_rl_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_1_pot_rl_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_1_pot_rl_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_rear_1_pot_rr_voltage_rr_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_1_pot_rr_voltage_rr_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_1_pot_rr_voltage_rr_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_rear_1_brake_pressure_rear_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_1_brake_pressure_rear_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_1_brake_pressure_rear_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int sc22_evo_canlv_sens_rear_3_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_sens_rear_3_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->straingauge_push_rr_voltage_m_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->straingauge_push_rr_voltage_m_v, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->straingauge_tie_rr_voltage_m_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->straingauge_tie_rr_voltage_m_v, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->straingauge_push_rl_voltage_m_v, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->straingauge_push_rl_voltage_m_v, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->straingauge_tie_rl_voltage_m_v, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->straingauge_tie_rl_voltage_m_v, 8u, 0xffu);

    return (8);
}

int sc22_evo_canlv_sens_rear_3_unpack(
    struct sc22_evo_canlv_sens_rear_3_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->straingauge_push_rr_voltage_m_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->straingauge_push_rr_voltage_m_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->straingauge_tie_rr_voltage_m_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->straingauge_tie_rr_voltage_m_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->straingauge_push_rl_voltage_m_v = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->straingauge_push_rl_voltage_m_v |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->straingauge_tie_rl_voltage_m_v = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->straingauge_tie_rl_voltage_m_v |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

uint16_t sc22_evo_canlv_sens_rear_3_straingauge_push_rr_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_3_straingauge_push_rr_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_3_straingauge_push_rr_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_rear_3_straingauge_tie_rr_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_3_straingauge_tie_rr_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_3_straingauge_tie_rr_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_rear_3_straingauge_push_rl_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_3_straingauge_push_rl_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_3_straingauge_push_rl_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_rear_3_straingauge_tie_rl_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_3_straingauge_tie_rl_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_3_straingauge_tie_rl_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int sc22_evo_canlv_sens_rear_2_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_sens_rear_2_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    dst_p[0] |= pack_left_shift_u16(src_p->cooling_pressure_dx_voltage_m_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->cooling_pressure_dx_voltage_m_v, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->cooling_pressure_sx_voltage_m_v, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->cooling_pressure_sx_voltage_m_v, 8u, 0xffu);

    return (4);
}

int sc22_evo_canlv_sens_rear_2_unpack(
    struct sc22_evo_canlv_sens_rear_2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 4u) {
        return (-EINVAL);
    }

    dst_p->cooling_pressure_dx_voltage_m_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->cooling_pressure_dx_voltage_m_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->cooling_pressure_sx_voltage_m_v = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->cooling_pressure_sx_voltage_m_v |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);

    return (0);
}

uint16_t sc22_evo_canlv_sens_rear_2_cooling_pressure_dx_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_2_cooling_pressure_dx_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_2_cooling_pressure_dx_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t sc22_evo_canlv_sens_rear_2_cooling_pressure_sx_voltage_m_v_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_2_cooling_pressure_sx_voltage_m_v_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_2_cooling_pressure_sx_voltage_m_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int sc22_evo_canlv_sens_rear_ntc_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_sens_rear_ntc_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->ntc_1_resistance, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->ntc_1_resistance, 8u, 0x03u);
    dst_p[1] |= pack_left_shift_u16(src_p->ntc_2_resistance, 2u, 0xfcu);
    dst_p[2] |= pack_right_shift_u16(src_p->ntc_2_resistance, 6u, 0x0fu);
    dst_p[2] |= pack_left_shift_u16(src_p->ntc_3_resistance, 4u, 0xf0u);
    dst_p[3] |= pack_right_shift_u16(src_p->ntc_3_resistance, 4u, 0x3fu);
    dst_p[3] |= pack_left_shift_u16(src_p->ntc_4_resistance, 6u, 0xc0u);
    dst_p[4] |= pack_right_shift_u16(src_p->ntc_4_resistance, 2u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->ntc_5_resistance, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->ntc_5_resistance, 8u, 0x03u);
    dst_p[6] |= pack_left_shift_u16(src_p->ntc_6_resistance, 2u, 0xfcu);
    dst_p[7] |= pack_right_shift_u16(src_p->ntc_6_resistance, 6u, 0x0fu);

    return (8);
}

int sc22_evo_canlv_sens_rear_ntc_unpack(
    struct sc22_evo_canlv_sens_rear_ntc_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ntc_1_resistance = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->ntc_1_resistance |= unpack_left_shift_u16(src_p[1], 8u, 0x03u);
    dst_p->ntc_2_resistance = unpack_right_shift_u16(src_p[1], 2u, 0xfcu);
    dst_p->ntc_2_resistance |= unpack_left_shift_u16(src_p[2], 6u, 0x0fu);
    dst_p->ntc_3_resistance = unpack_right_shift_u16(src_p[2], 4u, 0xf0u);
    dst_p->ntc_3_resistance |= unpack_left_shift_u16(src_p[3], 4u, 0x3fu);
    dst_p->ntc_4_resistance = unpack_right_shift_u16(src_p[3], 6u, 0xc0u);
    dst_p->ntc_4_resistance |= unpack_left_shift_u16(src_p[4], 2u, 0xffu);
    dst_p->ntc_5_resistance = unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->ntc_5_resistance |= unpack_left_shift_u16(src_p[6], 8u, 0x03u);
    dst_p->ntc_6_resistance = unpack_right_shift_u16(src_p[6], 2u, 0xfcu);
    dst_p->ntc_6_resistance |= unpack_left_shift_u16(src_p[7], 6u, 0x0fu);

    return (0);
}

uint16_t sc22_evo_canlv_sens_rear_ntc_ntc_1_resistance_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_ntc_ntc_1_resistance_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_ntc_ntc_1_resistance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t sc22_evo_canlv_sens_rear_ntc_ntc_2_resistance_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_ntc_ntc_2_resistance_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_ntc_ntc_2_resistance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t sc22_evo_canlv_sens_rear_ntc_ntc_3_resistance_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_ntc_ntc_3_resistance_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_ntc_ntc_3_resistance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t sc22_evo_canlv_sens_rear_ntc_ntc_4_resistance_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_ntc_ntc_4_resistance_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_ntc_ntc_4_resistance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t sc22_evo_canlv_sens_rear_ntc_ntc_5_resistance_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_ntc_ntc_5_resistance_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_ntc_ntc_5_resistance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

uint16_t sc22_evo_canlv_sens_rear_ntc_ntc_6_resistance_encode(float value)
{
    return (uint16_t)(value);
}

float sc22_evo_canlv_sens_rear_ntc_ntc_6_resistance_decode(uint16_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_ntc_ntc_6_resistance_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int sc22_evo_canlv_sens_rear_shutdown_status_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_sens_rear_shutdown_status_t *src_p,
    size_t size)
{
    uint8_t is_bsp_din_error;
    uint8_t is_shut_closed_post_bspd;
    uint8_t is_shut_closed_post_inv_fr;
    uint8_t is_shut_closed_post_inv_mono;
    uint8_t is_shut_closed_pre_funghi;

    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    is_shut_closed_post_bspd = (uint8_t)src_p->is_shut_closed_post_bspd;
    dst_p[0] |= pack_left_shift_u8(is_shut_closed_post_bspd, 0u, 0x01u);
    is_shut_closed_pre_funghi = (uint8_t)src_p->is_shut_closed_pre_funghi;
    dst_p[0] |= pack_left_shift_u8(is_shut_closed_pre_funghi, 1u, 0x02u);
    is_shut_closed_post_inv_mono = (uint8_t)src_p->is_shut_closed_post_inv_mono;
    dst_p[0] |= pack_left_shift_u8(is_shut_closed_post_inv_mono, 2u, 0x04u);
    is_shut_closed_post_inv_fr = (uint8_t)src_p->is_shut_closed_post_inv_fr;
    dst_p[0] |= pack_left_shift_u8(is_shut_closed_post_inv_fr, 3u, 0x08u);
    is_bsp_din_error = (uint8_t)src_p->is_bsp_din_error;
    dst_p[0] |= pack_left_shift_u8(is_bsp_din_error, 4u, 0x10u);

    return (1);
}

int sc22_evo_canlv_sens_rear_shutdown_status_unpack(
    struct sc22_evo_canlv_sens_rear_shutdown_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t is_bsp_din_error;
    uint8_t is_shut_closed_post_bspd;
    uint8_t is_shut_closed_post_inv_fr;
    uint8_t is_shut_closed_post_inv_mono;
    uint8_t is_shut_closed_pre_funghi;

    if (size < 1u) {
        return (-EINVAL);
    }

    is_shut_closed_post_bspd = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    if ((is_shut_closed_post_bspd & (1u << 0)) != 0u) {
        is_shut_closed_post_bspd |= 0xfeu;
    }

    dst_p->is_shut_closed_post_bspd = (int8_t)is_shut_closed_post_bspd;
    is_shut_closed_pre_funghi = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    if ((is_shut_closed_pre_funghi & (1u << 0)) != 0u) {
        is_shut_closed_pre_funghi |= 0xfeu;
    }

    dst_p->is_shut_closed_pre_funghi = (int8_t)is_shut_closed_pre_funghi;
    is_shut_closed_post_inv_mono = unpack_right_shift_u8(src_p[0], 2u, 0x04u);

    if ((is_shut_closed_post_inv_mono & (1u << 0)) != 0u) {
        is_shut_closed_post_inv_mono |= 0xfeu;
    }

    dst_p->is_shut_closed_post_inv_mono = (int8_t)is_shut_closed_post_inv_mono;
    is_shut_closed_post_inv_fr = unpack_right_shift_u8(src_p[0], 3u, 0x08u);

    if ((is_shut_closed_post_inv_fr & (1u << 0)) != 0u) {
        is_shut_closed_post_inv_fr |= 0xfeu;
    }

    dst_p->is_shut_closed_post_inv_fr = (int8_t)is_shut_closed_post_inv_fr;
    is_bsp_din_error = unpack_right_shift_u8(src_p[0], 4u, 0x10u);

    if ((is_bsp_din_error & (1u << 0)) != 0u) {
        is_bsp_din_error |= 0xfeu;
    }

    dst_p->is_bsp_din_error = (int8_t)is_bsp_din_error;

    return (0);
}

int8_t sc22_evo_canlv_sens_rear_shutdown_status_is_shut_closed_post_bspd_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_sens_rear_shutdown_status_is_shut_closed_post_bspd_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_shutdown_status_is_shut_closed_post_bspd_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_sens_rear_shutdown_status_is_shut_closed_pre_funghi_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_sens_rear_shutdown_status_is_shut_closed_pre_funghi_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_shutdown_status_is_shut_closed_pre_funghi_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_sens_rear_shutdown_status_is_shut_closed_post_inv_mono_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_sens_rear_shutdown_status_is_shut_closed_post_inv_mono_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_shutdown_status_is_shut_closed_post_inv_mono_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_sens_rear_shutdown_status_is_shut_closed_post_inv_fr_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_sens_rear_shutdown_status_is_shut_closed_post_inv_fr_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_shutdown_status_is_shut_closed_post_inv_fr_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_sens_rear_shutdown_status_is_bsp_din_error_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_sens_rear_shutdown_status_is_bsp_din_error_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_sens_rear_shutdown_status_is_bsp_din_error_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int sc22_evo_canlv_tlb_battery_tsal_status_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_tlb_battery_tsal_status_t *src_p,
    size_t size)
{
    uint8_t implausibility_is_air_neg_imp_present;
    uint8_t implausibility_is_air_pos_imp_present;
    uint8_t implausibility_is_any_imp_latched;
    uint8_t implausibility_is_any_imp_present;
    uint8_t implausibility_is_dc_bus_voltage_imp_present;
    uint8_t implausibility_is_relay_precharge_imp_present;
    uint8_t intentional_state_air_neg;
    uint8_t intentional_state_air_pos;
    uint8_t intentional_state_relay_precharge;
    uint8_t scs_is_any_short2_gnd_present;
    uint8_t scs_short2_gnd_air_neg;
    uint8_t scs_short2_gnd_air_pos;
    uint8_t tsal_is_air_neg_closed;
    uint8_t tsal_is_air_pos_closed;
    uint8_t tsal_is_dc_bus_over60_v;
    uint8_t tsal_is_green_on;
    uint8_t tsal_is_relay_precharge_closed;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    tsal_is_green_on = (uint8_t)src_p->tsal_is_green_on;
    dst_p[0] |= pack_left_shift_u8(tsal_is_green_on, 0u, 0x01u);
    tsal_is_air_pos_closed = (uint8_t)src_p->tsal_is_air_pos_closed;
    dst_p[0] |= pack_left_shift_u8(tsal_is_air_pos_closed, 1u, 0x02u);
    tsal_is_air_neg_closed = (uint8_t)src_p->tsal_is_air_neg_closed;
    dst_p[0] |= pack_left_shift_u8(tsal_is_air_neg_closed, 2u, 0x04u);
    tsal_is_relay_precharge_closed = (uint8_t)src_p->tsal_is_relay_precharge_closed;
    dst_p[0] |= pack_left_shift_u8(tsal_is_relay_precharge_closed, 3u, 0x08u);
    tsal_is_dc_bus_over60_v = (uint8_t)src_p->tsal_is_dc_bus_over60_v;
    dst_p[0] |= pack_left_shift_u8(tsal_is_dc_bus_over60_v, 4u, 0x10u);
    intentional_state_air_pos = (uint8_t)src_p->intentional_state_air_pos;
    dst_p[1] |= pack_left_shift_u8(intentional_state_air_pos, 0u, 0x01u);
    intentional_state_air_neg = (uint8_t)src_p->intentional_state_air_neg;
    dst_p[1] |= pack_left_shift_u8(intentional_state_air_neg, 1u, 0x02u);
    intentional_state_relay_precharge = (uint8_t)src_p->intentional_state_relay_precharge;
    dst_p[1] |= pack_left_shift_u8(intentional_state_relay_precharge, 2u, 0x04u);
    scs_short2_gnd_air_pos = (uint8_t)src_p->scs_short2_gnd_air_pos;
    dst_p[2] |= pack_left_shift_u8(scs_short2_gnd_air_pos, 0u, 0x01u);
    scs_short2_gnd_air_neg = (uint8_t)src_p->scs_short2_gnd_air_neg;
    dst_p[2] |= pack_left_shift_u8(scs_short2_gnd_air_neg, 1u, 0x02u);
    scs_is_any_short2_gnd_present = (uint8_t)src_p->scs_is_any_short2_gnd_present;
    dst_p[2] |= pack_left_shift_u8(scs_is_any_short2_gnd_present, 3u, 0x08u);
    implausibility_is_any_imp_present = (uint8_t)src_p->implausibility_is_any_imp_present;
    dst_p[3] |= pack_left_shift_u8(implausibility_is_any_imp_present, 0u, 0x01u);
    implausibility_is_air_pos_imp_present = (uint8_t)src_p->implausibility_is_air_pos_imp_present;
    dst_p[3] |= pack_left_shift_u8(implausibility_is_air_pos_imp_present, 1u, 0x02u);
    implausibility_is_air_neg_imp_present = (uint8_t)src_p->implausibility_is_air_neg_imp_present;
    dst_p[3] |= pack_left_shift_u8(implausibility_is_air_neg_imp_present, 2u, 0x04u);
    implausibility_is_relay_precharge_imp_present = (uint8_t)src_p->implausibility_is_relay_precharge_imp_present;
    dst_p[3] |= pack_left_shift_u8(implausibility_is_relay_precharge_imp_present, 3u, 0x08u);
    implausibility_is_dc_bus_voltage_imp_present = (uint8_t)src_p->implausibility_is_dc_bus_voltage_imp_present;
    dst_p[3] |= pack_left_shift_u8(implausibility_is_dc_bus_voltage_imp_present, 4u, 0x10u);
    implausibility_is_any_imp_latched = (uint8_t)src_p->implausibility_is_any_imp_latched;
    dst_p[3] |= pack_left_shift_u8(implausibility_is_any_imp_latched, 5u, 0x20u);

    return (4);
}

int sc22_evo_canlv_tlb_battery_tsal_status_unpack(
    struct sc22_evo_canlv_tlb_battery_tsal_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t implausibility_is_air_neg_imp_present;
    uint8_t implausibility_is_air_pos_imp_present;
    uint8_t implausibility_is_any_imp_latched;
    uint8_t implausibility_is_any_imp_present;
    uint8_t implausibility_is_dc_bus_voltage_imp_present;
    uint8_t implausibility_is_relay_precharge_imp_present;
    uint8_t intentional_state_air_neg;
    uint8_t intentional_state_air_pos;
    uint8_t intentional_state_relay_precharge;
    uint8_t scs_is_any_short2_gnd_present;
    uint8_t scs_short2_gnd_air_neg;
    uint8_t scs_short2_gnd_air_pos;
    uint8_t tsal_is_air_neg_closed;
    uint8_t tsal_is_air_pos_closed;
    uint8_t tsal_is_dc_bus_over60_v;
    uint8_t tsal_is_green_on;
    uint8_t tsal_is_relay_precharge_closed;

    if (size < 4u) {
        return (-EINVAL);
    }

    tsal_is_green_on = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    if ((tsal_is_green_on & (1u << 0)) != 0u) {
        tsal_is_green_on |= 0xfeu;
    }

    dst_p->tsal_is_green_on = (int8_t)tsal_is_green_on;
    tsal_is_air_pos_closed = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    if ((tsal_is_air_pos_closed & (1u << 0)) != 0u) {
        tsal_is_air_pos_closed |= 0xfeu;
    }

    dst_p->tsal_is_air_pos_closed = (int8_t)tsal_is_air_pos_closed;
    tsal_is_air_neg_closed = unpack_right_shift_u8(src_p[0], 2u, 0x04u);

    if ((tsal_is_air_neg_closed & (1u << 0)) != 0u) {
        tsal_is_air_neg_closed |= 0xfeu;
    }

    dst_p->tsal_is_air_neg_closed = (int8_t)tsal_is_air_neg_closed;
    tsal_is_relay_precharge_closed = unpack_right_shift_u8(src_p[0], 3u, 0x08u);

    if ((tsal_is_relay_precharge_closed & (1u << 0)) != 0u) {
        tsal_is_relay_precharge_closed |= 0xfeu;
    }

    dst_p->tsal_is_relay_precharge_closed = (int8_t)tsal_is_relay_precharge_closed;
    tsal_is_dc_bus_over60_v = unpack_right_shift_u8(src_p[0], 4u, 0x10u);

    if ((tsal_is_dc_bus_over60_v & (1u << 0)) != 0u) {
        tsal_is_dc_bus_over60_v |= 0xfeu;
    }

    dst_p->tsal_is_dc_bus_over60_v = (int8_t)tsal_is_dc_bus_over60_v;
    intentional_state_air_pos = unpack_right_shift_u8(src_p[1], 0u, 0x01u);

    if ((intentional_state_air_pos & (1u << 0)) != 0u) {
        intentional_state_air_pos |= 0xfeu;
    }

    dst_p->intentional_state_air_pos = (int8_t)intentional_state_air_pos;
    intentional_state_air_neg = unpack_right_shift_u8(src_p[1], 1u, 0x02u);

    if ((intentional_state_air_neg & (1u << 0)) != 0u) {
        intentional_state_air_neg |= 0xfeu;
    }

    dst_p->intentional_state_air_neg = (int8_t)intentional_state_air_neg;
    intentional_state_relay_precharge = unpack_right_shift_u8(src_p[1], 2u, 0x04u);

    if ((intentional_state_relay_precharge & (1u << 0)) != 0u) {
        intentional_state_relay_precharge |= 0xfeu;
    }

    dst_p->intentional_state_relay_precharge = (int8_t)intentional_state_relay_precharge;
    scs_short2_gnd_air_pos = unpack_right_shift_u8(src_p[2], 0u, 0x01u);

    if ((scs_short2_gnd_air_pos & (1u << 0)) != 0u) {
        scs_short2_gnd_air_pos |= 0xfeu;
    }

    dst_p->scs_short2_gnd_air_pos = (int8_t)scs_short2_gnd_air_pos;
    scs_short2_gnd_air_neg = unpack_right_shift_u8(src_p[2], 1u, 0x02u);

    if ((scs_short2_gnd_air_neg & (1u << 0)) != 0u) {
        scs_short2_gnd_air_neg |= 0xfeu;
    }

    dst_p->scs_short2_gnd_air_neg = (int8_t)scs_short2_gnd_air_neg;
    scs_is_any_short2_gnd_present = unpack_right_shift_u8(src_p[2], 3u, 0x08u);

    if ((scs_is_any_short2_gnd_present & (1u << 0)) != 0u) {
        scs_is_any_short2_gnd_present |= 0xfeu;
    }

    dst_p->scs_is_any_short2_gnd_present = (int8_t)scs_is_any_short2_gnd_present;
    implausibility_is_any_imp_present = unpack_right_shift_u8(src_p[3], 0u, 0x01u);

    if ((implausibility_is_any_imp_present & (1u << 0)) != 0u) {
        implausibility_is_any_imp_present |= 0xfeu;
    }

    dst_p->implausibility_is_any_imp_present = (int8_t)implausibility_is_any_imp_present;
    implausibility_is_air_pos_imp_present = unpack_right_shift_u8(src_p[3], 1u, 0x02u);

    if ((implausibility_is_air_pos_imp_present & (1u << 0)) != 0u) {
        implausibility_is_air_pos_imp_present |= 0xfeu;
    }

    dst_p->implausibility_is_air_pos_imp_present = (int8_t)implausibility_is_air_pos_imp_present;
    implausibility_is_air_neg_imp_present = unpack_right_shift_u8(src_p[3], 2u, 0x04u);

    if ((implausibility_is_air_neg_imp_present & (1u << 0)) != 0u) {
        implausibility_is_air_neg_imp_present |= 0xfeu;
    }

    dst_p->implausibility_is_air_neg_imp_present = (int8_t)implausibility_is_air_neg_imp_present;
    implausibility_is_relay_precharge_imp_present = unpack_right_shift_u8(src_p[3], 3u, 0x08u);

    if ((implausibility_is_relay_precharge_imp_present & (1u << 0)) != 0u) {
        implausibility_is_relay_precharge_imp_present |= 0xfeu;
    }

    dst_p->implausibility_is_relay_precharge_imp_present = (int8_t)implausibility_is_relay_precharge_imp_present;
    implausibility_is_dc_bus_voltage_imp_present = unpack_right_shift_u8(src_p[3], 4u, 0x10u);

    if ((implausibility_is_dc_bus_voltage_imp_present & (1u << 0)) != 0u) {
        implausibility_is_dc_bus_voltage_imp_present |= 0xfeu;
    }

    dst_p->implausibility_is_dc_bus_voltage_imp_present = (int8_t)implausibility_is_dc_bus_voltage_imp_present;
    implausibility_is_any_imp_latched = unpack_right_shift_u8(src_p[3], 5u, 0x20u);

    if ((implausibility_is_any_imp_latched & (1u << 0)) != 0u) {
        implausibility_is_any_imp_latched |= 0xfeu;
    }

    dst_p->implausibility_is_any_imp_latched = (int8_t)implausibility_is_any_imp_latched;

    return (0);
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_green_on_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_green_on_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_green_on_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_air_pos_closed_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_air_pos_closed_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_air_pos_closed_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_air_neg_closed_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_air_neg_closed_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_air_neg_closed_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_relay_precharge_closed_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_relay_precharge_closed_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_relay_precharge_closed_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_dc_bus_over60_v_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_dc_bus_over60_v_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_tsal_is_dc_bus_over60_v_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_intentional_state_air_pos_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_intentional_state_air_pos_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_intentional_state_air_pos_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_intentional_state_air_neg_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_intentional_state_air_neg_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_intentional_state_air_neg_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_intentional_state_relay_precharge_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_intentional_state_relay_precharge_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_intentional_state_relay_precharge_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_scs_short2_gnd_air_pos_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_scs_short2_gnd_air_pos_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_scs_short2_gnd_air_pos_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_scs_short2_gnd_air_neg_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_scs_short2_gnd_air_neg_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_scs_short2_gnd_air_neg_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_scs_is_any_short2_gnd_present_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_scs_is_any_short2_gnd_present_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_scs_is_any_short2_gnd_present_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_any_imp_present_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_any_imp_present_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_any_imp_present_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_air_pos_imp_present_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_air_pos_imp_present_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_air_pos_imp_present_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_air_neg_imp_present_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_air_neg_imp_present_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_air_neg_imp_present_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_relay_precharge_imp_present_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_relay_precharge_imp_present_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_relay_precharge_imp_present_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_dc_bus_voltage_imp_present_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_dc_bus_voltage_imp_present_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_dc_bus_voltage_imp_present_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_any_imp_latched_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_any_imp_latched_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_tsal_status_implausibility_is_any_imp_latched_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int sc22_evo_canlv_tlb_battery_shut_status_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_tlb_battery_shut_status_t *src_p,
    size_t size)
{
    uint8_t is_ams_error_latched;
    uint8_t is_imd_error_latched;
    uint8_t is_shut_closed_post_ams_latch;
    uint8_t is_shut_closed_post_imd_latch;
    uint8_t is_shut_closed_pre_ams_imd_latch;
    uint8_t is_shutdown_closed_pre_tlb_batt_final;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    is_shut_closed_pre_ams_imd_latch = (uint8_t)src_p->is_shut_closed_pre_ams_imd_latch;
    dst_p[0] |= pack_left_shift_u8(is_shut_closed_pre_ams_imd_latch, 0u, 0x01u);
    is_shut_closed_post_ams_latch = (uint8_t)src_p->is_shut_closed_post_ams_latch;
    dst_p[0] |= pack_left_shift_u8(is_shut_closed_post_ams_latch, 1u, 0x02u);
    is_shut_closed_post_imd_latch = (uint8_t)src_p->is_shut_closed_post_imd_latch;
    dst_p[0] |= pack_left_shift_u8(is_shut_closed_post_imd_latch, 2u, 0x04u);
    is_shutdown_closed_pre_tlb_batt_final = (uint8_t)src_p->is_shutdown_closed_pre_tlb_batt_final;
    dst_p[0] |= pack_left_shift_u8(is_shutdown_closed_pre_tlb_batt_final, 3u, 0x08u);
    is_ams_error_latched = (uint8_t)src_p->is_ams_error_latched;
    dst_p[0] |= pack_left_shift_u8(is_ams_error_latched, 4u, 0x10u);
    is_imd_error_latched = (uint8_t)src_p->is_imd_error_latched;
    dst_p[0] |= pack_left_shift_u8(is_imd_error_latched, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->shutdown_adc_post_sd_precharge_relay, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->shutdown_adc_ai_rs_opening_delay_capacitors, 0u, 0xffu);

    return (3);
}

int sc22_evo_canlv_tlb_battery_shut_status_unpack(
    struct sc22_evo_canlv_tlb_battery_shut_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t is_ams_error_latched;
    uint8_t is_imd_error_latched;
    uint8_t is_shut_closed_post_ams_latch;
    uint8_t is_shut_closed_post_imd_latch;
    uint8_t is_shut_closed_pre_ams_imd_latch;
    uint8_t is_shutdown_closed_pre_tlb_batt_final;

    if (size < 3u) {
        return (-EINVAL);
    }

    is_shut_closed_pre_ams_imd_latch = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    if ((is_shut_closed_pre_ams_imd_latch & (1u << 0)) != 0u) {
        is_shut_closed_pre_ams_imd_latch |= 0xfeu;
    }

    dst_p->is_shut_closed_pre_ams_imd_latch = (int8_t)is_shut_closed_pre_ams_imd_latch;
    is_shut_closed_post_ams_latch = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    if ((is_shut_closed_post_ams_latch & (1u << 0)) != 0u) {
        is_shut_closed_post_ams_latch |= 0xfeu;
    }

    dst_p->is_shut_closed_post_ams_latch = (int8_t)is_shut_closed_post_ams_latch;
    is_shut_closed_post_imd_latch = unpack_right_shift_u8(src_p[0], 2u, 0x04u);

    if ((is_shut_closed_post_imd_latch & (1u << 0)) != 0u) {
        is_shut_closed_post_imd_latch |= 0xfeu;
    }

    dst_p->is_shut_closed_post_imd_latch = (int8_t)is_shut_closed_post_imd_latch;
    is_shutdown_closed_pre_tlb_batt_final = unpack_right_shift_u8(src_p[0], 3u, 0x08u);

    if ((is_shutdown_closed_pre_tlb_batt_final & (1u << 0)) != 0u) {
        is_shutdown_closed_pre_tlb_batt_final |= 0xfeu;
    }

    dst_p->is_shutdown_closed_pre_tlb_batt_final = (int8_t)is_shutdown_closed_pre_tlb_batt_final;
    is_ams_error_latched = unpack_right_shift_u8(src_p[0], 4u, 0x10u);

    if ((is_ams_error_latched & (1u << 0)) != 0u) {
        is_ams_error_latched |= 0xfeu;
    }

    dst_p->is_ams_error_latched = (int8_t)is_ams_error_latched;
    is_imd_error_latched = unpack_right_shift_u8(src_p[0], 5u, 0x20u);

    if ((is_imd_error_latched & (1u << 0)) != 0u) {
        is_imd_error_latched |= 0xfeu;
    }

    dst_p->is_imd_error_latched = (int8_t)is_imd_error_latched;
    dst_p->shutdown_adc_post_sd_precharge_relay = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->shutdown_adc_ai_rs_opening_delay_capacitors = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int8_t sc22_evo_canlv_tlb_battery_shut_status_is_shut_closed_pre_ams_imd_latch_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_shut_status_is_shut_closed_pre_ams_imd_latch_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_shut_status_is_shut_closed_pre_ams_imd_latch_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_shut_status_is_shut_closed_post_ams_latch_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_shut_status_is_shut_closed_post_ams_latch_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_shut_status_is_shut_closed_post_ams_latch_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_shut_status_is_shut_closed_post_imd_latch_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_shut_status_is_shut_closed_post_imd_latch_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_shut_status_is_shut_closed_post_imd_latch_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_shut_status_is_shutdown_closed_pre_tlb_batt_final_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_shut_status_is_shutdown_closed_pre_tlb_batt_final_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_shut_status_is_shutdown_closed_pre_tlb_batt_final_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_shut_status_is_ams_error_latched_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_shut_status_is_ams_error_latched_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_shut_status_is_ams_error_latched_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_tlb_battery_shut_status_is_imd_error_latched_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_tlb_battery_shut_status_is_imd_error_latched_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_shut_status_is_imd_error_latched_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

uint8_t sc22_evo_canlv_tlb_battery_shut_status_shutdown_adc_post_sd_precharge_relay_encode(float value)
{
    return (uint8_t)(value);
}

float sc22_evo_canlv_tlb_battery_shut_status_shutdown_adc_post_sd_precharge_relay_decode(uint8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_shut_status_shutdown_adc_post_sd_precharge_relay_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc22_evo_canlv_tlb_battery_shut_status_shutdown_adc_ai_rs_opening_delay_capacitors_encode(float value)
{
    return (uint8_t)(value);
}

float sc22_evo_canlv_tlb_battery_shut_status_shutdown_adc_ai_rs_opening_delay_capacitors_decode(uint8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_tlb_battery_shut_status_shutdown_adc_ai_rs_opening_delay_capacitors_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sc22_evo_canlv_d_space_peripherals_ctrl_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_d_space_peripherals_ctrl_t *src_p,
    size_t size)
{
    uint8_t brake_light_on_ctrl;

    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    brake_light_on_ctrl = (uint8_t)src_p->brake_light_on_ctrl;
    dst_p[0] |= pack_left_shift_u8(brake_light_on_ctrl, 0u, 0x01u);
    dst_p[1] |= pack_left_shift_u8(src_p->rad_fan_pwm_ctrl, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->batt_hv_fan_ctrl, 0u, 0xffu);

    return (3);
}

int sc22_evo_canlv_d_space_peripherals_ctrl_unpack(
    struct sc22_evo_canlv_d_space_peripherals_ctrl_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t brake_light_on_ctrl;

    if (size < 3u) {
        return (-EINVAL);
    }

    brake_light_on_ctrl = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    if ((brake_light_on_ctrl & (1u << 0)) != 0u) {
        brake_light_on_ctrl |= 0xfeu;
    }

    dst_p->brake_light_on_ctrl = (int8_t)brake_light_on_ctrl;
    dst_p->rad_fan_pwm_ctrl = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->batt_hv_fan_ctrl = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int8_t sc22_evo_canlv_d_space_peripherals_ctrl_brake_light_on_ctrl_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_d_space_peripherals_ctrl_brake_light_on_ctrl_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_d_space_peripherals_ctrl_brake_light_on_ctrl_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

uint8_t sc22_evo_canlv_d_space_peripherals_ctrl_rad_fan_pwm_ctrl_encode(float value)
{
    return (uint8_t)(value);
}

float sc22_evo_canlv_d_space_peripherals_ctrl_rad_fan_pwm_ctrl_decode(uint8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_d_space_peripherals_ctrl_rad_fan_pwm_ctrl_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t sc22_evo_canlv_d_space_peripherals_ctrl_batt_hv_fan_ctrl_encode(float value)
{
    return (uint8_t)(value);
}

float sc22_evo_canlv_d_space_peripherals_ctrl_batt_hv_fan_ctrl_decode(uint8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_d_space_peripherals_ctrl_batt_hv_fan_ctrl_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int sc22_evo_canlv_d_space_rtd_ack_pack(
    uint8_t *dst_p,
    const struct sc22_evo_canlv_d_space_rtd_ack_t *src_p,
    size_t size)
{
    uint8_t ctor_en_ack;
    uint8_t reboot_fsm;
    uint8_t rtd_en_ack;

    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    ctor_en_ack = (uint8_t)src_p->ctor_en_ack;
    dst_p[0] |= pack_left_shift_u8(ctor_en_ack, 0u, 0x01u);
    rtd_en_ack = (uint8_t)src_p->rtd_en_ack;
    dst_p[0] |= pack_left_shift_u8(rtd_en_ack, 1u, 0x02u);
    reboot_fsm = (uint8_t)src_p->reboot_fsm;
    dst_p[0] |= pack_left_shift_u8(reboot_fsm, 2u, 0x04u);

    return (1);
}

int sc22_evo_canlv_d_space_rtd_ack_unpack(
    struct sc22_evo_canlv_d_space_rtd_ack_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t ctor_en_ack;
    uint8_t reboot_fsm;
    uint8_t rtd_en_ack;

    if (size < 1u) {
        return (-EINVAL);
    }

    ctor_en_ack = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    if ((ctor_en_ack & (1u << 0)) != 0u) {
        ctor_en_ack |= 0xfeu;
    }

    dst_p->ctor_en_ack = (int8_t)ctor_en_ack;
    rtd_en_ack = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    if ((rtd_en_ack & (1u << 0)) != 0u) {
        rtd_en_ack |= 0xfeu;
    }

    dst_p->rtd_en_ack = (int8_t)rtd_en_ack;
    reboot_fsm = unpack_right_shift_u8(src_p[0], 2u, 0x04u);

    if ((reboot_fsm & (1u << 0)) != 0u) {
        reboot_fsm |= 0xfeu;
    }

    dst_p->reboot_fsm = (int8_t)reboot_fsm;

    return (0);
}

int8_t sc22_evo_canlv_d_space_rtd_ack_ctor_en_ack_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_d_space_rtd_ack_ctor_en_ack_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_d_space_rtd_ack_ctor_en_ack_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_d_space_rtd_ack_rtd_en_ack_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_d_space_rtd_ack_rtd_en_ack_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_d_space_rtd_ack_rtd_en_ack_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}

int8_t sc22_evo_canlv_d_space_rtd_ack_reboot_fsm_encode(float value)
{
    return (int8_t)(value);
}

float sc22_evo_canlv_d_space_rtd_ack_reboot_fsm_decode(int8_t value)
{
    return ((float)value);
}

bool sc22_evo_canlv_d_space_rtd_ack_reboot_fsm_is_in_range(int8_t value)
{
    return ((value >= 0) && (value <= 1));
}
